[package]
name = "harvest-chart-server"
default-run = "harvest-chart-server"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "=2.0.2", features = ["sqlite", "r2d2"] }
diesel_migrations = "=2.0.0"

# this has to be within the allowed versions for diesel-rs - note we're on the 1.4.x branch (latest stable)
# see https://github.com/diesel-rs/diesel/blob/1.4.x/diesel/Cargo.toml#L19
libsqlite3-sys = { version = "=0.25.2", features = ["bundled"] }

actix-cors = "=0.6.4"
actix-web = "=4.2.1"
anyhow = "=1.0.66"
base64 = "=0.13.1"
chrono = "=0.4.23"
clap = {version = "=4.0.29", features = ["cargo"] }
dotenv-build = "=0.1.1"
env_logger = "=0.10.0"
expiring_map = { git = "https://github.com/larsonmpdx/expiring_map/", branch = "remove_item" }
git2 = "=0.15.0"
indexmap = "=1.9.2"
itertools = "=0.10.5"
json5 = "=0.4.1"
lazy_static = "=1.4.0"
more-asserts = "=0.3"
oauth2 = "=4.3.0"
once_cell = "=1.16.0"
pathdiff = "=0.2.1"
rand = "=0.8.5"
regex = "=1.7.0"
reqwest = "=0.11.13"
serde = {version = "=1.0.148", features = ["derive"] }
serde_derive = "=1.0.148"
serde_json = "=1.0.89"
serde_with = "=2.1.0"
urlencoding = "=2.1.2"
walkdir = "=2.3.2"

[build-dependencies]
dotenv-build = "=0.1.1"
