[package]
name = "harvest-chart-server"
default-run = "harvest-chart-server"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
actix-cors = "0.6.1"
libsqlite3-sys = { version = "0.22.0", features = ["bundled"] }
diesel = { version = "1.4.8", features = ["sqlite", "r2d2"] }
diesel_migrations = "1.4"
serde = {version = "1.0", features = ["derive"] }
serde_with = "1.9.1"
serde_json = "1.0"
serde_derive = "1.0"
json5 = "0.4.1"
clap = {version = "3.0", features = ["cargo"] }
chrono = "0.4"
more-asserts = "0.2"
regex = "1.5.4"
walkdir = "2"
lazy_static = "1.4.0"
itertools = "0.10.1"
dotenv = "0.15"
git2 = "0.14"
pathdiff = "0.2.0"
anyhow = "1.0.55"
oauth2 = "4.1.0"
rand = "0.8.4"
expiring_map = { git = "https://github.com/larsonmpdx/expiring_map/", branch = "remove_item" }
once_cell = "1.9.0"
base64 = "0.13.0"
reqwest = "0.11.7"
indexmap = "1.8.1"
env_logger = "0.9.0"
urlencoding = "2.1.0"

[build-dependencies]
dotenv-build = "0.1"