// created by import_db.rs - don't edit

pub const TYPES: &[&str] = &[
    "Apple",
    "Apricot",
    "Asian Pear",
    "Euro Pear",
    "Euro Plum",
    "Japanese Plum",
    "Sour Cherry",
    "Sweet Cherry",
    "Nectarine",
    "Peach",
    "Fig",
    "Apriplum",
    "Plumcot",
    "Blueberry",
    "Hardy Kiwi",
    "Fuzzy Kiwi",
    "Muscadine",
    "Grape",
    "Elderberry",
    "Strawberry",
    "Raspberry",
    "Blackberry",
    "Gooseberry",
    "Currant",
    "Saskatoon",
    "Hazelnut",
    "Walnut",
    "Almond",
    "Chestnut",
    "Pistachio",
    "Pecan",
    "Citrus",
    "Sweet Orange",
    "Lemon",
    "Lime",
    "Kumquat",
    "Tangelo",
    "Clementine",
    "Grapefruit",
    "Mandarin",
    "Quince",
    "Pawpaw",
    "Crabapple",
    "Jujube",
    "Persimmon",
    "Nanking Cherry",
    "Mulberry",
    "Pomegranate",
    "Olive",
    "Prunus Rootstock",
];
