// diesel requires us to maintain two copies of everything:
// * the database schema in "up.sql" which becomes schema_generated.rs, generated by diesel-cli
// * plus this file with rust structs, made by hand to match
//   * there's a 3rd copy, in the json struct in import_db.rs, that won't match exactly because we translate or fill in some things to make the json form simpler

#[derive(Queryable)]
pub struct PlantType {
    pub plant_type_id: i32,
    pub name: String,
    pub latin_name: Option<String>,
}

#[derive(Queryable)]
pub struct BasePlant {
    pub plant_id: i32,
    pub name: String,
    pub type_: String,
    pub description: Option<String>,
    pub patent: Option<String>,
    pub relative_harvest: Option<String>,
    pub harvest_start: Option<i32>,
    pub harvest_end: Option<i32>,
}

#[derive(Queryable)]
pub struct CollectionItems {
    pub collection_item_id: i32,
    pub collection_id: String,
    pub note: Option<String>,
    pub name: String,
    pub type_: String,
    pub description: Option<String>,
    pub patent: Option<String>,
    pub relative_harvest: Option<String>,
    pub harvest_start: Option<i32>,
    pub harvest_end: Option<i32>,
}

#[derive(Queryable)]
pub struct Collections {
    pub collection_id: i32,
    pub user_id: i32,
    pub name: String,
    pub path: Option<String>,
    pub title: Option<String>,
    pub author: Option<String>,
    pub note: Option<String>,
    pub url: Option<String>,
    pub published: Option<String>,
    pub reviewed: Option<String>,
    pub accessed: Option<String>,
    pub location: Option<String>,
    pub latitude: Option<f64>,
    pub longitude: Option<f64>,
}

#[derive(Queryable)]
pub struct Users {
    pub user_id: i32,
    pub name: String,
}
