// rust diesel requires us to maintain two copies of everything, the database schema description plus this matching rust struct
// schema.rs is automatically generated by diesel-cli

#[derive(Queryable)]
pub struct PlantType {
    pub id: Option<i32>,
    pub name: String,
    pub latin_name: Option<String>,
}
