name: backend test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: copy env
      run: cp ./.env.example ./.env
      working-directory: ./backend
    - name: Build
      run: cargo build --verbose
      working-directory: ./backend
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./backend
