name: backend test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # in order to get enough git history to extract our git commit number etc. done in tests
    - name: copy env
      run: cp ./.env.example ./.env
    - name: copy demo file
      run: cp ./src/gazetteer_load/test_data_file.txt.demo ./src/gazetteer_load/2021_Gaz_zcta_national.txt
    - name: Build
      run: cargo build # can add "--verbose" flag
    - name: Run tests
      run: cargo test -- --include-ignored # can add "--verbose" flag
