name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x' # match version in get_ubuntu_dependencies.sh
    - run: npm install # not "npm ci" because I'm not using a lockfile
    - run: npm run build
    - run: npm test
